name: Standalone

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: apt-update
      run: sudo apt-get update -qq
    # - name: apt get glfw
    #   run: sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libglew-dev
    - name: apt get xrandr
      run: sudo apt-get install -y --no-install-recommends libxrandr-dev

    - name: configure
      run: cmake -Hstandalone -Bbuild

    - name: build
      run: cmake --build build -j4

    - name: run
      run: ./build/Greeter
