name: Standalone

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: apt-update
      run: sudo apt-get update -qq
    - name: gcc update
      run: sudo apt-get install gcc
    - name: get dependencies
      run: sudo apt-get install -y libglfw3 libglfw3-dev
    # - name: get dependencies
    #   run: sudo apt-get install -y --no-install-recommends libxrandr-dev libxinerama-dev

    - name: configure
      run: cmake -Hstandalone/Terrain -Bbuild

    - name: build
      run: cmake --build build -j4

    # - name: run # Display is not supported in git actions
    #   run: ./build/Terrain
